### ISSUE TITLE
Ember relationship b/w Users<>UsersBoxes<>Boxes breaks Add Permission

### ISSUE THREAD

**Issue by ismurray** [ismurray/whats-mine-client#2]
I have a many to many relationship between Users and Boxes through UsersBoxes. I've been trying all day to make this relationship work and I can't figure it out. I need to be able to create a new UsersBox entry to give another user 'ownership' of a Box, so that more than one User can 'own' a shared box. 

models/user.js
```
import DS from 'ember-data'

export default DS.Model.extend({
  email: DS.attr('string'),
  items: DS.attr(),
  boxes: DS.hasMany('box'),
  permissions: DS.hasMany('users-box', { inverse: 'user' })
})
```
models/box.js
```
import DS from 'ember-data'

export default DS.Model.extend({
  name: DS.attr('string'),
  items: DS.hasMany('item'),
  users: DS.hasMany('user'),
  permissions: DS.hasMany('users-box', { inverse: 'box' })
})
```
models/users-box.js
```
import DS from 'ember-data'

export default DS.Model.extend({
  writeAccess: DS.attr(),
  user_id: DS.attr(),
  box_id: DS.attr(),
  user: DS.belongsTo('user', { inverse: 'permissions' }),
  box: DS.belongsTo('box', { inverse: 'permissions' })
})
```
The relevant action in the route: routes/boxes/edit.js
```

    createUsersBox (usersBoxPojo) {
      console.log('in the route babyyy', usersBoxPojo)
      const usersBox = this.get('store').createRecord('users-box', usersBoxPojo)
      usersBox.save()
        .then((usersBox) => this.transitionTo('/boxes/' + usersBox.get('box_id')))
    }

```
From the route template: 
```
<h5>Share this Box with another User:</h5>
{{invite-users-box box=model
                   addUserToBox='createUsersBox'}}
```
The relevant component.js 
```
import Component from '@ember/component'

export default Component.extend({
  didInsertElement () {
    this.set('newUsersBox', {
      user_id: null,
      box_id: null,
      writeAccess: false
    })
  },
  actions: {
    addUserToBox (box) {
      console.log('writeAccess is', this.get('newUsersBox.writeAccess'))
      console.log('user_id is', this.get('newUsersBox.user_id'))
      this.set('newUsersBox.box_id', box.get('id'))
      console.log('box_id is', this.get('newUsersBox.box_id'))
      this.sendAction('addUserToBox', this.get('newUsersBox'))
    }
  }
})
```
The component .hbs
```
<form {{action "addUserToBox" box on="submit"}}>
  {{input placeholder="Enter other User's ID" value=newUsersBox.user_id}}
  <div>
     {{input type="checkbox" name="writeAccess" checked=newUsersBox.writeAccess}}
     Give Write Access (Added User will have Read-Only Access if unchecked)
  </div>

  <button>Add User</button>
</form>

```
The browser console error I keep getting when I try to add a UsersBox:
```
rsvp.js:27 Uncaught ErrorClass {isAdapterError: true, stack: "Error: The adapter rejected the commit because it …(http://localhost:7165/assets/vendor.js:10318:14)", description: undefined, fileName: undefined, lineNumber: undefined, …}code: undefineddescription: undefinederrors: []fileName: undefinedisAdapterError: truelineNumber: undefinedmessage: "The adapter rejected the commit because it was invalid"name: "Error"number: undefinedstack: "Error: The adapter rejected the commit because it was invalid↵    at ErrorClass.EmberError (http://localhost:7165/assets/vendor.js:24962:25)↵    at ErrorClass.AdapterError (http://localhost:7165/assets/vendor.js:91383:15)↵    at new ErrorClass (http://localhost:7165/assets/vendor.js:91404:22)↵    at Class.handleResponse (http://localhost:7165/assets/vendor.js:70073:16)↵    at Class.superWrapper [as handleResponse] (http://localhost:7165/assets/vendor.js:56456:22)↵    at ajaxError (http://localhost:7165/assets/vendor.js:103866:25)↵    at Class.hash.error (http://localhost:7165/assets/vendor.js:103533:23)↵    at fire (http://localhost:7165/assets/vendor.js:4279:31)↵    at Object.fireWith [as rejectWith] (http://localhost:7165/assets/vendor.js:4409:7)↵    at done (http://localhost:7165/assets/vendor.js:10318:14)"__proto__: EmberError
```
My server error:
```
Started POST "/users_boxes" for ::1 at 2018-04-16 16:08:16 -0400
Processing by UsersBoxesController#create as HTML
  Parameters: {"users_box"=>{"write_access"=>false, "user_id"=>nil, "box_id"=>nil}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."token" = $1 LIMIT $2  [["token", "1303eabbb4d65cb97165556a77110e96"], ["LIMIT", 1]]
"original params are "
<ActionController::Parameters {"users_box"=>{"write_access"=>false, "user_id"=>nil, "box_id"=>nil}, "controller"=>"users_boxes", "action"=>"create", "format"=>"json"} permitted: false>
"original params are "
<ActionController::Parameters {"users_box"=><ActionController::Parameters {"write_access"=>false, "user_id"=>nil, "box_id"=>nil} permitted: false>, "controller"=>"users_boxes", "action"=>"create", "format"=>"json"} permitted: false>
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
[active_model_serializers] Rendered ActiveModel::Serializer::Null with ActiveModel::Errors (0.06ms)
Completed 422 Unprocessable Entity in 5ms (Views: 0.4ms | ActiveRecord: 0.5ms)
```
Note the `Parameters: {"users_box"=>{"write_access"=>false, "user_id"=>nil, "box_id"=>nil}}`

Something is wrong with the way the record is being created, as the user_id and box_id are getting to the API as nil.

The console log at the top of the `createUsersBox` action method looks good. Here's an example:
```
in the route babyyy 
{box_id: "3"}
box_id
:
"3"
user_id
:
"3"
writeAccess
:
false
get user_id
:
ƒ GETTER_FUNCTION()
set user_id
:
ƒ SETTER_FUNCTION(value)
get writeAccess
:
ƒ GETTER_FUNCTION()
set writeAccess
:
ƒ SETTER_FUNCTION(value)
__proto__
:
Object
```

But, something weird and Embery is happening and these values are being lost between that point and the server, since the server is getting `Parameters: {"users_box"=>{"write_access"=>false, "user_id"=>nil, "box_id"=>nil}}`

**Comment by ismurray** [comment]
If I remove the relationship from my Ember model, it works(below). But I need the relationship to be able to access the update the permissions.
user model:
```
import DS from 'ember-data'

export default DS.Model.extend({
  email: DS.attr('string'),
  items: DS.attr(),
  boxes: DS.hasMany('box')
  // permissions: DS.hasMany('users-box', { inverse: 'user' })
})

```

box model:
```
import DS from 'ember-data'

export default DS.Model.extend({
  name: DS.attr('string'),
  items: DS.hasMany('item'),
  users: DS.hasMany('user')
  // permissions: DS.hasMany('users-box', { inverse: 'box' })
})

```

users-box model
```
import DS from 'ember-data'

export default DS.Model.extend({
  writeAccess: DS.attr(),
  user_id: DS.attr(),
  box_id: DS.attr()
  // user: DS.belongsTo('user', { inverse: 'permissions' }),
  // box: DS.belongsTo('box', { inverse: 'permissions' })
})
```

**Comment by ismurray** [comment]
I also tried changing the route method to this with no luck:
```
createUsersBox (usersBoxPojo) {
      console.log('in the route babyyy', usersBoxPojo)
      const usersBox = this.get('store').createRecord('users-box', usersBoxPojo)
      this.get('store').findRecord('user', usersBoxPojo.user_id).then(function (user) {
        usersBox.set('user', user)
      })
      this.get('store').findRecord('box', usersBoxPojo.box_id).then(function (box) {
        usersBox.set('box', box)
      })
      usersBox.save()
        .then((usersBox) => this.transitionTo('/boxes/' + usersBox.get('box_id')))
    }
```
